dist: ./bin
before:
  hooks:
    - go mod download -x
builds:
  - main: ./cmd/husky
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - riscv64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/go-courier/husky/version.Version={{ .Version }}+sha.{{ .FullCommit }}
    mod_timestamp: '{{ .CommitTimestamp }}'
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'